version: '3.8'

services:
  php-apache:
    build: .
    ports:
      - "8080:80"                    # Le site sera accessible sur http://localhost:8080
    volumes:
      - .:/var/www/html             # Le code est monté dans le conteneur
    depends_on:
      - mysql
      - mongo

  mysql:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urbages_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d  # Execute init.sql au démarrage

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
  mongo_data: